### ISSUE TITLE
// trigger phrase not triggering popup

### ISSUE THREAD

**Issue by theapiarist** [ycnmhd/obsidian-enhanced-annotations#20]
On Obsidian v1.7.7 (on OS X) typing `//` does not trigger the popup menu. I've tried with a new vault and no other community plugins installed. The autocomplete check is ON and I've tried using both HTML and Obsidian-type comments. I've also tried with Slash commands in Core plugins checked and unchecked.

CMD-P Enhanced annotation menu items are listed and appear to work as expected.

Do I need another Obsidian plugin (Text-Expander?) or similar for this functionality to work? 

With thanks

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified the onTrigger method in the AnnotationSuggest class to ensure the autocomplete popup triggers correctly when typing '//'.

You can review changes in this commit: https://github.com/lattaai13/ycnmhd-obsidian-enhanced-annotations-20/commit/865329e930921d23da0a036c036aa2b7e328ab6c.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by ycnmhd** [comment]
After testing the plugin in a new vault, I noticed that the popup only shows up after the user has created at least one label (in the styles settings).
Once the popup started showing up, I was able to create new labels from within the popup itself.
This could be improved by always showing an "unlabeled" option.

**Comment by theapiarist** [comment]
Many thanks ... that appears to work 👍 .
