### ISSUE TITLE
[Feature Request] Allow to keep the original highlight style on the file in live preview mode

### ISSUE THREAD

**Issue by dolores824** [ycnmhd/obsidian-enhanced-annotations#4]
First really appreciate your work on this plugin, it's been super helpful and really makes a difference on the note-taking workflow.

Just wondering would it be possible to introduce an option to allow users to toggle between to show the plugin's highlight style or keep the original highlight style. This would offer more flexibility to various preferences.

Thanks again for your work!

**Comment by ycnmhd** [comment]
I think it's a bug.
The plugin should not style highlights unless the user creates an unlabeled style, or the highlighted text is prefixed with a label that has a style.
![image](https://github.com/ycnmhd/obsidian-enhanced-annotations/assets/33285087/84a5b569-f84b-4356-975f-75269e939053)

The bug is causing the plugin to automatically create a style for unlabeled highlights.

**Comment by ycnmhd** [comment]
Update the plugin and see if it's fixed.
Thank you for reporting it!

Edit: make sure that the unlabeled style is deleted
